Increase MaxMetaspaceSize
Attempt to resolve error:
  Error: Exception in thread "Daemon client event forwarder" java.lang.OutOfMemoryError: Java heap space
	  at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1661)
	  at java.base/java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:460)
	  at org.gradle.launcher.daemon.server.exec.DaemonConnectionBackedEventConsumer$ForwardEvents.getNextEvent(DaemonConnectionBackedEventConsumer.java:72)
  	  at org.gradle.launcher.daemon.server.exec.DaemonConnectionBackedEventConsumer$ForwardEvents.run(DaemonConnectionBackedEventConsumer.java:59)
  The Daemon will expire immediately since the JVM garbage collector is thrashing.
  The project memory settings are likely not configured or are configured to an insufficient value.
  The memory settings for this project must be adjusted to avoid this failure.
  These settings can be adjusted by setting 'org.gradle.jvmargs' in 'gradle.properties'.
  The currently configured max heap space is '512 MiB' and the configured max metaspace is '512 MiB'.